#include <string.h>


int main()
{
    char * ptr;
    memcpy(ptr, "hello", 5);

    return 0;    
}

// Core was generated by `./app'.
// Program terminated with signal SIGSEGV, Segmentation fault.
// gdb app
// core-file core.32186 即可